eureka:
  client:
    service-url:
      default: http://localhost:8761/eureka
server:
  port: 9009
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
      - id: STOCK-PRICE-CALC
        uri: http://localhost:9091
